"""
AI Service — Local LLM assistant via LM Studio.

All AI processing runs on the shop computer. The LLM is accessed through
LM Studio's OpenAI-compatible API (default: http://localhost:1234/v1).

Architecture:
  - Read-only data access: the AI can query any table but never writes
  - Tool-calling pattern: the LLM is given function descriptions and can
    request data fetches, which we execute and feed back into the conversation
  - Cached results: anomaly/prediction outputs are stored in ai_cached_results
  - Ephemeral conversations: chat history lives in-memory on the backend,
    keyed by a session token; nothing is persisted to disk

Security:
  - Zero cloud dependency — all traffic stays on localhost / LAN
  - All SQL generated by the AI is validated to be SELECT-only
  - The use_ai permission controls access
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timedelta, timezone
from typing import Any

import aiosqlite
import httpx

logger = logging.getLogger(__name__)

# ── LM Studio Client Config ─────────────────────────────────────

DEFAULT_LM_STUDIO_URL = "http://localhost:1234/v1"
REQUEST_TIMEOUT = 120.0  # seconds — LLMs can be slow on CPU

# ── System Prompts ───────────────────────────────────────────────

SYSTEM_PROMPT = """You are a helpful AI assistant for an electrical contracting company's management system called "Wired-Part". You have read-only access to company data through tools.

RULES:
1. Always use the provided tools to fetch data before answering questions. Never guess or fabricate data.
2. You can ONLY READ data. You cannot create, update, or delete any records.
3. Keep answers concise and practical — these are busy tradespeople.
4. When showing numbers, use plain language (e.g., "32 hours" not "32.00000 hrs").
5. If you're unsure or the data doesn't support a clear answer, say so honestly.
6. Reference specific names, job numbers, and dates when available.
7. Format currency as $X,XXX.XX and hours as Xh Xm.
8. For tables of data, use markdown tables.

COMPANY CONTEXT:
- This is an electrical contracting company
- "Jobs" are construction/service job sites
- "JPO" = Job Parts Order (field worker requests parts)
- "PO" = Purchase Order (office sends to supplier)
- Workers clock in/out of jobs with GPS
- Parts are tracked by category > style > type > color
- The warehouse tracks stock movements and bin locations
"""

ANOMALY_SYSTEM_PROMPT = """You are an anomaly detection system for an electrical contracting company. Analyze the provided data and identify unusual patterns that warrant attention.

Focus on:
- Overtime anomalies: workers exceeding their typical hours
- Cost anomalies: jobs with spending spikes vs historical averages
- Schedule anomalies: unusual patterns in assignments or clock-ins
- Inventory anomalies: stock levels below usage-rate thresholds

For each anomaly, provide:
- A short title (under 80 chars)
- A clear explanation of what's unusual and why it matters
- A severity level: info (FYI), warning (needs attention), critical (urgent)
- The relevant category: labor, parts, scheduling, or costs

Return ONLY valid JSON as an array of objects with keys: title, body, severity, category, context
"""

PREDICTION_SYSTEM_PROMPT = """You are a predictive ordering system for an electrical contracting company. Based on historical parts usage data, predict what parts will be needed in the coming weeks.

For each prediction, provide:
- A short title (under 80 chars)
- A clear recommendation with quantities and reasoning
- The relevant part categories and suppliers if applicable

Return ONLY valid JSON as an array of objects with keys: title, body, category, context
"""

SUMMARY_SYSTEM_PROMPT = """You are a report summarizer for an electrical contracting company. Generate a clear, readable summary of the provided report data.

Guidelines:
- Lead with the most important numbers
- Mention specific workers, jobs, and amounts
- Flag anything unusual (high OT, budget overruns, etc.)
- Keep it to 2-3 short paragraphs maximum
- Write in plain business English, not technical jargon
"""


# ── Tool Definitions (for function calling) ──────────────────────

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "query_labor",
            "description": "Get labor hours, clock-in/out records for employees or jobs. Can filter by date range.",
            "parameters": {
                "type": "object",
                "properties": {
                    "employee_id": {"type": "integer", "description": "Filter by specific employee/user ID"},
                    "employee_name": {"type": "string", "description": "Filter by employee name (partial match)"},
                    "job_id": {"type": "integer", "description": "Filter by specific job ID"},
                    "start_date": {"type": "string", "description": "Start date (YYYY-MM-DD)"},
                    "end_date": {"type": "string", "description": "End date (YYYY-MM-DD)"},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_jobs",
            "description": "Get job details including name, status, job number, address, and budget info.",
            "parameters": {
                "type": "object",
                "properties": {
                    "job_id": {"type": "integer", "description": "Specific job ID"},
                    "status": {"type": "string", "description": "Filter by status: active, completed, on_hold, cancelled"},
                    "search": {"type": "string", "description": "Search job name or number"},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_parts_stock",
            "description": "Get current stock levels for parts in the warehouse. Shows part name, quantity, bin location.",
            "parameters": {
                "type": "object",
                "properties": {
                    "part_id": {"type": "integer", "description": "Specific part ID"},
                    "category": {"type": "string", "description": "Part category name"},
                    "low_stock_only": {"type": "boolean", "description": "Only show items below minimum stock level"},
                    "search": {"type": "string", "description": "Search part description"},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_parts_usage",
            "description": "Get parts usage/consumption history — what parts were pulled for which jobs and when.",
            "parameters": {
                "type": "object",
                "properties": {
                    "job_id": {"type": "integer", "description": "Filter by job"},
                    "part_id": {"type": "integer", "description": "Filter by specific part"},
                    "start_date": {"type": "string", "description": "Start date (YYYY-MM-DD)"},
                    "end_date": {"type": "string", "description": "End date (YYYY-MM-DD)"},
                    "days": {"type": "integer", "description": "Look back N days from today"},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_orders",
            "description": "Get purchase order (PO) and job parts order (JPO) status and details.",
            "parameters": {
                "type": "object",
                "properties": {
                    "po_id": {"type": "integer", "description": "Specific PO ID"},
                    "status": {"type": "string", "description": "Filter by status: draft, pending_approval, approved, sent, received, etc."},
                    "supplier": {"type": "string", "description": "Filter by supplier name"},
                    "start_date": {"type": "string", "description": "Created after this date (YYYY-MM-DD)"},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_schedule",
            "description": "Get scheduling/dispatch assignments — who is assigned to which job on which date.",
            "parameters": {
                "type": "object",
                "properties": {
                    "date": {"type": "string", "description": "Specific date (YYYY-MM-DD)"},
                    "employee_id": {"type": "integer", "description": "Filter by employee"},
                    "job_id": {"type": "integer", "description": "Filter by job"},
                    "week_of": {"type": "string", "description": "Get full week starting from this date (YYYY-MM-DD)"},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_costs",
            "description": "Get cost tracking data — labor costs, parts costs, budget vs actual for jobs.",
            "parameters": {
                "type": "object",
                "properties": {
                    "job_id": {"type": "integer", "description": "Specific job to get costs for"},
                    "period": {"type": "string", "description": "Time period: 'this_week', 'last_week', 'this_month', 'last_month', 'ytd'"},
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "query_employees",
            "description": "Get employee/user information including name, role, certifications, and skills.",
            "parameters": {
                "type": "object",
                "properties": {
                    "employee_id": {"type": "integer", "description": "Specific employee ID"},
                    "search": {"type": "string", "description": "Search by name"},
                    "active_only": {"type": "boolean", "description": "Only active employees (default true)"},
                },
            },
        },
    },
]


# ── SQL for each tool ────────────────────────────────────────────

def _build_labor_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for labor entries."""
    sql = """
        SELECT le.id, u.display_name AS employee, j.job_name AS job_name, j.job_number,
               le.clock_in, le.clock_out, le.regular_hours, le.overtime_hours, le.status
        FROM labor_entries le
        JOIN users u ON u.id = le.user_id
        JOIN jobs j ON j.id = le.job_id
        WHERE 1=1
    """
    args: list = []
    if params.get("employee_id"):
        sql += " AND le.user_id = ?"
        args.append(params["employee_id"])
    if params.get("employee_name"):
        sql += " AND u.display_name LIKE ?"
        args.append(f"%{params['employee_name']}%")
    if params.get("job_id"):
        sql += " AND le.job_id = ?"
        args.append(params["job_id"])
    if params.get("start_date"):
        sql += " AND le.clock_in >= ?"
        args.append(params["start_date"])
    if params.get("end_date"):
        sql += " AND le.clock_in <= ?"
        args.append(params["end_date"] + "T23:59:59")
    sql += " ORDER BY le.clock_in DESC LIMIT 100"
    return sql, args


def _build_jobs_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for jobs."""
    sql = """
        SELECT j.id, j.job_number, j.job_name, j.status, j.address_line1 AS address,
               j.budget_labor, j.budget_materials, j.created_at
        FROM jobs j
        WHERE 1=1
    """
    args: list = []
    if params.get("job_id"):
        sql += " AND j.id = ?"
        args.append(params["job_id"])
    if params.get("status"):
        sql += " AND j.status = ?"
        args.append(params["status"])
    if params.get("search"):
        sql += " AND (j.job_name LIKE ? OR j.job_number LIKE ?)"
        args.extend([f"%{params['search']}%", f"%{params['search']}%"])
    sql += " ORDER BY j.created_at DESC LIMIT 50"
    return sql, args


def _build_stock_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for stock levels."""
    sql = """
        SELECT s.id, p.description AS part_name, pc.name AS category,
               s.quantity_on_hand, s.minimum_stock, s.bin_location,
               s.quantity_on_hand - COALESCE(s.minimum_stock, 0) AS surplus
        FROM stock s
        JOIN parts p ON p.id = s.part_id
        LEFT JOIN part_types pt ON pt.id = p.part_type_id
        LEFT JOIN part_styles ps ON ps.id = pt.style_id
        LEFT JOIN part_categories pc ON pc.id = ps.category_id
        WHERE 1=1
    """
    args: list = []
    if params.get("part_id"):
        sql += " AND s.part_id = ?"
        args.append(params["part_id"])
    if params.get("category"):
        sql += " AND pc.name LIKE ?"
        args.append(f"%{params['category']}%")
    if params.get("low_stock_only"):
        sql += " AND s.quantity_on_hand < COALESCE(s.minimum_stock, 0)"
    if params.get("search"):
        sql += " AND p.description LIKE ?"
        args.append(f"%{params['search']}%")
    sql += " ORDER BY surplus ASC LIMIT 100"
    return sql, args


def _build_usage_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for parts usage (stock movements)."""
    days = params.get("days", 30)
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")

    sql = """
        SELECT sm.id, p.description AS part_name, j.job_name AS job_name,
               sm.quantity, sm.movement_type, sm.created_at,
               u.display_name AS moved_by
        FROM stock_movements sm
        JOIN parts p ON p.id = sm.part_id
        LEFT JOIN jobs j ON j.id = sm.job_id
        LEFT JOIN users u ON u.id = sm.user_id
        WHERE sm.created_at >= ?
    """
    args: list[Any] = [cutoff]
    if params.get("job_id"):
        sql += " AND sm.job_id = ?"
        args.append(params["job_id"])
    if params.get("part_id"):
        sql += " AND sm.part_id = ?"
        args.append(params["part_id"])
    if params.get("start_date"):
        sql = sql.replace(f"sm.created_at >= ?", "sm.created_at >= ?")
        args[0] = params["start_date"]
    if params.get("end_date"):
        sql += " AND sm.created_at <= ?"
        args.append(params["end_date"] + "T23:59:59")
    sql += " ORDER BY sm.created_at DESC LIMIT 200"
    return sql, args


def _build_orders_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for purchase orders."""
    sql = """
        SELECT po.id, po.po_number, po.status, po.supplier_name,
               po.total_amount, po.created_at, po.sent_at,
               u.display_name AS created_by
        FROM purchase_orders po
        LEFT JOIN users u ON u.id = po.created_by_id
        WHERE 1=1
    """
    args: list = []
    if params.get("po_id"):
        sql += " AND po.id = ?"
        args.append(params["po_id"])
    if params.get("status"):
        sql += " AND po.status = ?"
        args.append(params["status"])
    if params.get("supplier"):
        sql += " AND po.supplier_name LIKE ?"
        args.append(f"%{params['supplier']}%")
    if params.get("start_date"):
        sql += " AND po.created_at >= ?"
        args.append(params["start_date"])
    sql += " ORDER BY po.created_at DESC LIMIT 50"
    return sql, args


def _build_schedule_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for scheduling (daily dispatch)."""
    sql = """
        SELECT s.id, s.scheduled_date, u.display_name AS employee,
               j.job_name AS job_name, j.job_number, s.start_time, s.end_time,
               s.status, s.notes
        FROM scheduling s
        JOIN users u ON u.id = s.user_id
        JOIN jobs j ON j.id = s.job_id
        WHERE 1=1
    """
    args: list = []
    if params.get("date"):
        sql += " AND s.scheduled_date = ?"
        args.append(params["date"])
    if params.get("week_of"):
        end = (datetime.strptime(params["week_of"], "%Y-%m-%d") + timedelta(days=6)).strftime("%Y-%m-%d")
        sql += " AND s.scheduled_date BETWEEN ? AND ?"
        args.extend([params["week_of"], end])
    if params.get("employee_id"):
        sql += " AND s.user_id = ?"
        args.append(params["employee_id"])
    if params.get("job_id"):
        sql += " AND s.job_id = ?"
        args.append(params["job_id"])
    sql += " ORDER BY s.scheduled_date, s.start_time LIMIT 100"
    return sql, args


def _build_costs_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for cost data."""
    period = params.get("period", "this_month")
    now = datetime.now(timezone.utc)

    if period == "this_week":
        start = (now - timedelta(days=now.weekday())).strftime("%Y-%m-%d")
    elif period == "last_week":
        start = (now - timedelta(days=now.weekday() + 7)).strftime("%Y-%m-%d")
    elif period == "last_month":
        first_this = now.replace(day=1)
        last_prev = first_this - timedelta(days=1)
        start = last_prev.replace(day=1).strftime("%Y-%m-%d")
    elif period == "ytd":
        start = now.strftime("%Y-01-01")
    else:  # this_month
        start = now.strftime("%Y-%m-01")

    if params.get("job_id"):
        sql = """
            SELECT j.job_name AS job_name, j.job_number,
                   j.budget_labor, j.budget_materials,
                   COALESCE(SUM(le.regular_hours), 0) AS total_regular_hours,
                   COALESCE(SUM(le.overtime_hours), 0) AS total_overtime_hours,
                   COUNT(DISTINCT le.user_id) AS unique_workers
            FROM jobs j
            LEFT JOIN labor_entries le ON le.job_id = j.id AND le.clock_in >= ?
            WHERE j.id = ?
            GROUP BY j.id
        """
        args = [start, params["job_id"]]
    else:
        sql = """
            SELECT j.job_name AS job_name, j.job_number,
                   j.budget_labor, j.budget_materials,
                   COALESCE(SUM(le.regular_hours), 0) AS total_regular_hours,
                   COALESCE(SUM(le.overtime_hours), 0) AS total_overtime_hours,
                   COUNT(DISTINCT le.user_id) AS unique_workers
            FROM jobs j
            LEFT JOIN labor_entries le ON le.job_id = j.id AND le.clock_in >= ?
            WHERE j.status = 'active'
            GROUP BY j.id
            ORDER BY total_regular_hours DESC
            LIMIT 20
        """
        args = [start]
    return sql, args


def _build_employees_query(params: dict) -> tuple[str, list]:
    """Build SELECT query for employee info."""
    sql = """
        SELECT u.id, u.display_name, u.username, u.is_active,
               GROUP_CONCAT(DISTINCT h.name) AS hats
        FROM users u
        LEFT JOIN user_hats uh ON uh.user_id = u.id
        LEFT JOIN hats h ON h.id = uh.hat_id
        WHERE 1=1
    """
    args: list = []
    if params.get("employee_id"):
        sql += " AND u.id = ?"
        args.append(params["employee_id"])
    if params.get("search"):
        sql += " AND u.display_name LIKE ?"
        args.append(f"%{params['search']}%")
    if params.get("active_only", True):
        sql += " AND u.is_active = 1"
    sql += " GROUP BY u.id ORDER BY u.display_name LIMIT 50"
    return sql, args


# Tool name → query builder mapping
TOOL_QUERY_BUILDERS = {
    "query_labor": _build_labor_query,
    "query_jobs": _build_jobs_query,
    "query_parts_stock": _build_stock_query,
    "query_parts_usage": _build_usage_query,
    "query_orders": _build_orders_query,
    "query_schedule": _build_schedule_query,
    "query_costs": _build_costs_query,
    "query_employees": _build_employees_query,
}


# ── Context-Aware Prompt Suggestions ─────────────────────────────

CONTEXT_PROMPTS: dict[str, list[str]] = {
    "dashboard": [
        "Give me a quick summary of today's activity",
        "Which jobs had the most labor hours this week?",
        "Are there any anomalies I should know about?",
    ],
    "jobs": [
        "Which jobs are over budget?",
        "Labor summary for this week by job",
        "Which jobs have the most overtime?",
    ],
    "job_detail": [
        "Summarize the labor on this job",
        "What parts have been used on this job?",
        "How does this job compare to budget?",
    ],
    "parts": [
        "What parts are running low in stock?",
        "Show me parts usage for the last 30 days",
        "Which parts are used most frequently?",
    ],
    "warehouse": [
        "What's running low in the warehouse?",
        "Show me recent stock movements",
        "Which jobs consumed the most parts this week?",
    ],
    "orders": [
        "Show me all pending POs",
        "Which suppliers have outstanding orders?",
        "What's the total on open purchase orders?",
    ],
    "schedule": [
        "Who's scheduled for tomorrow?",
        "Show me this week's schedule",
        "Which jobs need more workers?",
    ],
    "people": [
        "Who worked the most hours this week?",
        "Show me overtime by employee",
        "Who has expiring certifications?",
    ],
    "costs": [
        "What's the total spending this month?",
        "Which job has the highest cost?",
        "Compare labor vs materials costs",
    ],
    "fleet": [
        "Which vehicles need maintenance?",
        "Show me mileage logs for this week",
        "What deliveries are pending?",
    ],
    "reports": [
        "Summarize yesterday's daily reports",
        "What were the key highlights this week?",
        "Show me labor hours by employee this period",
    ],
    "default": [
        "Show me a quick company overview",
        "What needs my attention today?",
        "Any anomalies in the past week?",
    ],
}

def get_context_prompts(page_context: str) -> list[str]:
    """Return suggested prompts for the given page context."""
    return CONTEXT_PROMPTS.get(page_context, CONTEXT_PROMPTS["default"])


# ── Main AI Service ──────────────────────────────────────────────

class AiService:
    """Local AI assistant with read-only data access via LM Studio."""

    def __init__(self, db: aiosqlite.Connection) -> None:
        self.db = db
        self.db.row_factory = aiosqlite.Row

    async def _get_lm_studio_url(self) -> str:
        """Read LM Studio URL from app settings, falling back to default."""
        try:
            cursor = await self.db.execute(
                "SELECT value FROM settings WHERE key = 'ai_lm_studio_url'"
            )
            row = await cursor.fetchone()
            if row and row[0]:
                return row[0].rstrip("/")
        except Exception:
            pass
        return DEFAULT_LM_STUDIO_URL.rstrip("/")

    async def _is_feature_enabled(self, feature_key: str) -> bool:
        """Check if a specific AI feature is enabled in settings."""
        try:
            cursor = await self.db.execute(
                "SELECT value FROM settings WHERE key = ?", (feature_key,)
            )
            row = await cursor.fetchone()
            return row is not None and row[0] == "true"
        except Exception:
            return False

    async def _is_ai_enabled(self) -> bool:
        """Check if the master AI toggle is on."""
        return await self._is_feature_enabled("ai_enabled")

    async def check_connection(self) -> dict:
        """Test connectivity to LM Studio and return model info."""
        url = await self._get_lm_studio_url()
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.get(f"{url}/models")
                if resp.status_code == 200:
                    data = resp.json()
                    models = data.get("data", [])
                    return {
                        "status": "connected",
                        "url": url,
                        "models": [m.get("id", "unknown") for m in models],
                        "model_count": len(models),
                    }
                return {"status": "error", "url": url, "error": f"HTTP {resp.status_code}"}
        except httpx.ConnectError:
            return {"status": "unreachable", "url": url, "error": "Cannot connect to LM Studio. Is it running?"}
        except Exception as exc:
            return {"status": "error", "url": url, "error": str(exc)}

    # ── Tool Execution ───────────────────────────────────────────

    async def _execute_tool(self, tool_name: str, arguments: dict) -> str:
        """Execute a read-only tool call and return results as formatted string."""
        builder = TOOL_QUERY_BUILDERS.get(tool_name)
        if not builder:
            return f"Unknown tool: {tool_name}"

        try:
            sql, args = builder(arguments)

            # Safety: verify query is SELECT-only
            normalized = sql.strip().upper()
            if not normalized.startswith("SELECT"):
                logger.warning("AI tried to run non-SELECT query: %s", sql[:100])
                return "Error: Only SELECT queries are allowed."

            # Block dangerous keywords
            dangerous = {"INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE", "ATTACH", "DETACH"}
            tokens = set(re.findall(r'\b[A-Z]+\b', normalized))
            if tokens & dangerous:
                logger.warning("AI query contains dangerous keyword: %s", tokens & dangerous)
                return "Error: Query contains forbidden operations."

            cursor = await self.db.execute(sql, args)
            rows = await cursor.fetchall()

            if not rows:
                return "No results found."

            # Convert to list of dicts
            columns = [desc[0] for desc in cursor.description]
            results = [dict(zip(columns, row)) for row in rows]

            # Format as readable text (not raw JSON — LLMs do better with tables)
            if len(results) <= 10:
                # Table format for small results
                header = " | ".join(columns)
                separator = "-|-".join("-" * len(c) for c in columns)
                data_rows = []
                for r in results:
                    data_rows.append(" | ".join(str(r.get(c, "")) for c in columns))
                return f"Results ({len(results)} rows):\n{header}\n{separator}\n" + "\n".join(data_rows)
            else:
                # Summary for large results
                return f"Results ({len(results)} rows):\n" + json.dumps(results, indent=2, default=str)

        except Exception as exc:
            logger.exception("Tool execution error for %s", tool_name)
            return f"Error executing {tool_name}: {str(exc)}"

    # ── Chat / Ask ───────────────────────────────────────────────

    async def ask(
        self,
        question: str,
        conversation_history: list[dict] | None = None,
        page_context: str | None = None,
    ) -> dict:
        """Answer a natural language question using data + LLM.

        Returns: {"answer": str, "tool_calls_made": int, "model": str}
        """
        if not await self._is_ai_enabled():
            return {"answer": "AI is currently disabled. Enable it in Settings → AI Config.", "tool_calls_made": 0, "model": "none"}

        url = await self._get_lm_studio_url()

        # Build messages
        messages = [{"role": "system", "content": SYSTEM_PROMPT}]

        # Add page context if available
        if page_context:
            ctx_msg = f"The user is currently viewing the '{page_context}' section of the application."
            messages.append({"role": "system", "content": ctx_msg})

        # Add conversation history (last 10 exchanges max)
        if conversation_history:
            for msg in conversation_history[-20:]:
                messages.append(msg)

        messages.append({"role": "user", "content": question})

        tool_calls_made = 0
        max_tool_rounds = 5  # Prevent infinite tool-calling loops
        model_used = "unknown"

        async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
            for _round in range(max_tool_rounds):
                try:
                    resp = await client.post(
                        f"{url}/chat/completions",
                        json={
                            "messages": messages,
                            "tools": TOOL_DEFINITIONS,
                            "tool_choice": "auto",
                            "temperature": 0.3,
                            "max_tokens": 2048,
                        },
                    )
                    resp.raise_for_status()
                    data = resp.json()
                except httpx.ConnectError:
                    return {
                        "answer": "Cannot reach LM Studio. Make sure it's running and a model is loaded.",
                        "tool_calls_made": tool_calls_made,
                        "model": "unreachable",
                    }
                except Exception as exc:
                    logger.exception("LM Studio request failed")
                    return {
                        "answer": f"AI request failed: {str(exc)}",
                        "tool_calls_made": tool_calls_made,
                        "model": "error",
                    }

                choice = data.get("choices", [{}])[0]
                message = choice.get("message", {})
                model_used = data.get("model", "unknown")

                # Check if the LLM wants to call tools
                tool_calls = message.get("tool_calls")
                if tool_calls:
                    # Add the assistant's tool-call message
                    messages.append(message)

                    for tc in tool_calls:
                        fn_name = tc["function"]["name"]
                        try:
                            fn_args = json.loads(tc["function"]["arguments"])
                        except (json.JSONDecodeError, KeyError):
                            fn_args = {}

                        logger.info("AI tool call: %s(%s)", fn_name, fn_args)
                        result = await self._execute_tool(fn_name, fn_args)
                        tool_calls_made += 1

                        messages.append({
                            "role": "tool",
                            "tool_call_id": tc["id"],
                            "content": result,
                        })

                    # Continue loop — LLM will process tool results
                    continue

                # No tool calls — we have the final answer
                answer = message.get("content", "I wasn't able to generate a response.")
                return {
                    "answer": answer,
                    "tool_calls_made": tool_calls_made,
                    "model": model_used,
                }

        return {
            "answer": "AI reached maximum tool-calling rounds without producing a final answer.",
            "tool_calls_made": tool_calls_made,
            "model": model_used,
        }

    # ── Report Summarization ─────────────────────────────────────

    async def summarize_report(self, report_type: str, data_context: dict) -> dict:
        """Generate a natural language summary of report data.

        report_type: 'daily', 'weekly', 'job_cost', 'pre_billing'
        data_context: pre-fetched data to summarize (passed to LLM as context)
        """
        if not await self._is_ai_enabled():
            return {"summary": "AI is disabled.", "model": "none"}

        if not await self._is_feature_enabled("ai_report_summaries"):
            return {"summary": "Report summaries are disabled in AI settings.", "model": "none"}

        url = await self._get_lm_studio_url()

        prompt = f"""Please summarize the following {report_type} report data:

{json.dumps(data_context, indent=2, default=str)}

Provide a concise, readable summary suitable for a manager or bookkeeper."""

        try:
            async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
                resp = await client.post(
                    f"{url}/chat/completions",
                    json={
                        "messages": [
                            {"role": "system", "content": SUMMARY_SYSTEM_PROMPT},
                            {"role": "user", "content": prompt},
                        ],
                        "temperature": 0.3,
                        "max_tokens": 1024,
                    },
                )
                resp.raise_for_status()
                result = resp.json()
                answer = result["choices"][0]["message"]["content"]
                return {"summary": answer, "model": result.get("model", "unknown")}
        except httpx.ConnectError:
            return {"summary": "Cannot reach LM Studio.", "model": "unreachable"}
        except Exception as exc:
            logger.exception("Report summarization failed")
            return {"summary": f"Summarization failed: {str(exc)}", "model": "error"}

    # ── Anomaly Detection ────────────────────────────────────────

    async def detect_anomalies(self) -> list[dict]:
        """Scan recent data for anomalies and return flagged items.

        This is designed to be called on a schedule (e.g., 4 AM daily).
        Results are cached in ai_cached_results.
        """
        if not await self._is_ai_enabled():
            return []
        if not await self._is_feature_enabled("ai_anomaly_detection"):
            return []

        url = await self._get_lm_studio_url()

        # ── Gather data context for anomaly detection ────────────
        context_sections = []

        # 1) Labor anomalies — this week vs 4-week average
        try:
            cursor = await self.db.execute("""
                SELECT u.display_name AS name,
                       SUM(CASE WHEN le.clock_in >= date('now', '-7 days') THEN le.regular_hours + le.overtime_hours ELSE 0 END) AS hours_this_week,
                       SUM(CASE WHEN le.clock_in >= date('now', '-7 days') THEN le.overtime_hours ELSE 0 END) AS ot_this_week,
                       SUM(le.regular_hours + le.overtime_hours) / 4.0 AS avg_weekly_hours,
                       SUM(le.overtime_hours) / 4.0 AS avg_weekly_ot
                FROM labor_entries le
                JOIN users u ON u.id = le.user_id
                WHERE le.clock_in >= date('now', '-28 days') AND le.status = 'completed'
                GROUP BY le.user_id
                HAVING hours_this_week > 0
            """)
            rows = await cursor.fetchall()
            if rows:
                columns = [d[0] for d in cursor.description]
                labor_data = [dict(zip(columns, r)) for r in rows]
                context_sections.append(f"LABOR DATA (this week vs 4-week avg):\n{json.dumps(labor_data, indent=2, default=str)}")
        except Exception as exc:
            logger.warning("Anomaly: labor data fetch failed: %s", exc)

        # 2) Stock anomalies — items below minimum
        try:
            cursor = await self.db.execute("""
                SELECT p.description, s.quantity_on_hand, s.minimum_stock,
                       s.quantity_on_hand - COALESCE(s.minimum_stock, 0) AS deficit
                FROM stock s
                JOIN parts p ON p.id = s.part_id
                WHERE s.minimum_stock > 0 AND s.quantity_on_hand < s.minimum_stock * 1.5
                ORDER BY deficit ASC LIMIT 20
            """)
            rows = await cursor.fetchall()
            if rows:
                columns = [d[0] for d in cursor.description]
                stock_data = [dict(zip(columns, r)) for r in rows]
                context_sections.append(f"LOW STOCK ITEMS:\n{json.dumps(stock_data, indent=2, default=str)}")
        except Exception as exc:
            logger.warning("Anomaly: stock data fetch failed: %s", exc)

        # 3) Job budget anomalies
        try:
            cursor = await self.db.execute("""
                SELECT j.job_name, j.job_number, j.budget_labor, j.budget_materials,
                       COALESCE(SUM(le.regular_hours + le.overtime_hours), 0) AS total_hours
                FROM jobs j
                LEFT JOIN labor_entries le ON le.job_id = j.id
                WHERE j.status = 'active' AND j.budget_labor > 0
                GROUP BY j.id
                HAVING total_hours > 0
            """)
            rows = await cursor.fetchall()
            if rows:
                columns = [d[0] for d in cursor.description]
                budget_data = [dict(zip(columns, r)) for r in rows]
                context_sections.append(f"JOB BUDGET DATA (active jobs with labor budgets):\n{json.dumps(budget_data, indent=2, default=str)}")
        except Exception as exc:
            logger.warning("Anomaly: budget data fetch failed: %s", exc)

        if not context_sections:
            return []

        # ── Send to LLM ─────────────────────────────────────────
        full_context = "\n\n".join(context_sections)
        prompt = f"""Analyze the following data and identify anomalies:

{full_context}

Return ONLY a valid JSON array. Each object must have: title, body, severity (info/warning/critical), category (labor/parts/scheduling/costs), context (object with relevant IDs).
If no anomalies are found, return an empty array: []"""

        try:
            async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
                resp = await client.post(
                    f"{url}/chat/completions",
                    json={
                        "messages": [
                            {"role": "system", "content": ANOMALY_SYSTEM_PROMPT},
                            {"role": "user", "content": prompt},
                        ],
                        "temperature": 0.2,
                        "max_tokens": 2048,
                    },
                )
                resp.raise_for_status()
                result = resp.json()
                content = result["choices"][0]["message"]["content"]

                # Parse JSON from response (handle markdown code blocks)
                content = content.strip()
                if content.startswith("```"):
                    content = re.sub(r"^```(?:json)?\s*", "", content)
                    content = re.sub(r"\s*```$", "", content)

                anomalies = json.loads(content)
                if not isinstance(anomalies, list):
                    anomalies = [anomalies]

                # Cache results
                await self._cache_results("anomaly", anomalies)
                return anomalies

        except json.JSONDecodeError as exc:
            logger.warning("AI anomaly response was not valid JSON: %s", exc)
            return []
        except httpx.ConnectError:
            logger.warning("LM Studio unreachable during anomaly detection")
            return []
        except Exception as exc:
            logger.exception("Anomaly detection failed")
            return []

    # ── Predictive Ordering ──────────────────────────────────────

    async def predict_ordering(self, days_ahead: int = 30) -> list[dict]:
        """Predict parts ordering needs based on usage patterns.

        Returns cached predictions or generates new ones via LLM.
        """
        if not await self._is_ai_enabled():
            return []
        if not await self._is_feature_enabled("ai_predictive_ordering"):
            return []

        url = await self._get_lm_studio_url()

        # Gather usage data (90 days lookback)
        try:
            cursor = await self.db.execute("""
                SELECT p.description AS part_name, pc.name AS category,
                       SUM(ABS(sm.quantity)) AS total_used_90d,
                       ROUND(SUM(ABS(sm.quantity)) / 90.0 * ?, 1) AS projected_need,
                       COALESCE(st.quantity_on_hand, 0) AS current_stock,
                       COALESCE(st.minimum_stock, 0) AS min_stock
                FROM stock_movements sm
                JOIN parts p ON p.id = sm.part_id
                LEFT JOIN part_types pt ON pt.id = p.part_type_id
                LEFT JOIN part_styles ps ON ps.id = pt.style_id
                LEFT JOIN part_categories pc ON pc.id = ps.category_id
                LEFT JOIN stock st ON st.part_id = p.id
                WHERE sm.movement_type IN ('pull', 'consume', 'job_pull')
                  AND sm.created_at >= date('now', '-90 days')
                GROUP BY sm.part_id
                HAVING total_used_90d > 0
                ORDER BY projected_need DESC
                LIMIT 50
            """, (days_ahead,))
            rows = await cursor.fetchall()
            if not rows:
                return []

            columns = [d[0] for d in cursor.description]
            usage_data = [dict(zip(columns, r)) for r in rows]
        except Exception as exc:
            logger.exception("Prediction: usage data fetch failed")
            return []

        prompt = f"""Based on the following 90-day parts usage data, predict what needs to be ordered for the next {days_ahead} days.

Compare projected needs against current stock levels. Focus on items where current stock won't last through the projection period.

DATA:
{json.dumps(usage_data, indent=2, default=str)}

Return ONLY a valid JSON array. Each object must have: title, body, category, context (with part names and quantities).
If no ordering is needed, return an empty array: []"""

        try:
            async with httpx.AsyncClient(timeout=REQUEST_TIMEOUT) as client:
                resp = await client.post(
                    f"{url}/chat/completions",
                    json={
                        "messages": [
                            {"role": "system", "content": PREDICTION_SYSTEM_PROMPT},
                            {"role": "user", "content": prompt},
                        ],
                        "temperature": 0.2,
                        "max_tokens": 2048,
                    },
                )
                resp.raise_for_status()
                result = resp.json()
                content = result["choices"][0]["message"]["content"]

                content = content.strip()
                if content.startswith("```"):
                    content = re.sub(r"^```(?:json)?\s*", "", content)
                    content = re.sub(r"\s*```$", "", content)

                predictions = json.loads(content)
                if not isinstance(predictions, list):
                    predictions = [predictions]

                await self._cache_results("prediction", predictions)
                return predictions

        except json.JSONDecodeError:
            logger.warning("AI prediction response was not valid JSON")
            return []
        except httpx.ConnectError:
            logger.warning("LM Studio unreachable during prediction")
            return []
        except Exception:
            logger.exception("Prediction generation failed")
            return []

    # ── Cached Results Management ────────────────────────────────

    async def _cache_results(self, result_type: str, items: list[dict]) -> None:
        """Store AI results in the cache table, replacing stale entries."""
        # Expire old entries of same type
        await self.db.execute(
            "DELETE FROM ai_cached_results WHERE result_type = ? AND is_dismissed = 0",
            (result_type,),
        )

        now = datetime.now(timezone.utc).isoformat()
        expires = (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()

        for item in items:
            await self.db.execute("""
                INSERT INTO ai_cached_results
                    (result_type, category, title, body, severity, context_json, expires_at, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                result_type,
                item.get("category", "general"),
                item.get("title", "Untitled"),
                item.get("body", ""),
                item.get("severity", "info"),
                json.dumps(item.get("context")) if item.get("context") else None,
                expires,
                now,
            ))
        await self.db.commit()

    async def get_cached_anomalies(self, include_dismissed: bool = False) -> list[dict]:
        """Retrieve cached anomaly results."""
        sql = """
            SELECT id, category, title, body, severity, context_json,
                   is_dismissed, created_at, expires_at
            FROM ai_cached_results
            WHERE result_type = 'anomaly'
              AND (expires_at IS NULL OR expires_at > datetime('now'))
        """
        if not include_dismissed:
            sql += " AND is_dismissed = 0"
        sql += " ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END, created_at DESC"

        cursor = await self.db.execute(sql)
        rows = await cursor.fetchall()
        columns = [d[0] for d in cursor.description]
        return [dict(zip(columns, r)) for r in rows]

    async def get_cached_predictions(self) -> list[dict]:
        """Retrieve cached ordering predictions."""
        cursor = await self.db.execute("""
            SELECT id, category, title, body, context_json, created_at, expires_at
            FROM ai_cached_results
            WHERE result_type = 'prediction'
              AND is_dismissed = 0
              AND (expires_at IS NULL OR expires_at > datetime('now'))
            ORDER BY created_at DESC
        """)
        rows = await cursor.fetchall()
        columns = [d[0] for d in cursor.description]
        return [dict(zip(columns, r)) for r in rows]

    async def dismiss_cached_result(self, result_id: int, user_id: int) -> bool:
        """Mark a cached anomaly/prediction as dismissed."""
        now = datetime.now(timezone.utc).isoformat()
        cursor = await self.db.execute("""
            UPDATE ai_cached_results
            SET is_dismissed = 1, dismissed_by = ?, dismissed_at = ?
            WHERE id = ? AND is_dismissed = 0
        """, (user_id, now, result_id))
        await self.db.commit()
        return cursor.rowcount > 0

    async def get_anomaly_count(self) -> int:
        """Get count of active (non-dismissed, non-expired) anomalies."""
        cursor = await self.db.execute("""
            SELECT COUNT(*) FROM ai_cached_results
            WHERE result_type = 'anomaly' AND is_dismissed = 0
              AND (expires_at IS NULL OR expires_at > datetime('now'))
        """)
        row = await cursor.fetchone()
        return row[0] if row else 0
