import Foundation
import CoreGraphics

// MARK: - Image Feature Adapter Protocol

/// Platform-specific image feature extraction interface.
///
/// Extracts feature vectors from images for similarity-based part matching.
///
/// Implementations:
/// - macOS/iOS: `VNGenerateImageFeaturePrintRequest` (Vision framework, 2048-dim)
/// - Windows: MobileNetV3-Small via ONNX Runtime (1024-dim)
///
/// Feature vectors from different adapters are NOT interchangeable.
/// The `adapter_type` column ensures vectors are only compared against
/// vectors generated by the same adapter.
public protocol ImageFeatureAdapter: AnyObject, Sendable {
    /// Whether feature extraction is available on this device.
    var isAvailable: Bool { get }

    /// Dimension of the feature vector (e.g. 2048 for VNFeaturePrint).
    var featureDimension: Int { get }

    /// Identifier for this adapter type (e.g. "apple_vision", "onnx_mobilenet").
    /// Used to ensure vectors are only compared against same-type vectors.
    var adapterType: String { get }

    /// Extract a feature vector from an image.
    ///
    /// - Parameter image: The input image.
    /// - Returns: A normalized feature vector of length `featureDimension`.
    func extractFeatures(from image: CGImage) async throws -> [Float]
}

// MARK: - Image Feature Errors

public enum ImageFeatureError: Error, LocalizedError, Sendable {
    case extractionNotAvailable
    case extractionFailed(String)
    case imageConversionFailed
    case invalidImageSize

    public var errorDescription: String? {
        switch self {
        case .extractionNotAvailable:
            return "Image feature extraction is not available on this device"
        case .extractionFailed(let reason):
            return "Feature extraction failed: \(reason)"
        case .imageConversionFailed:
            return "Failed to convert image for feature extraction"
        case .invalidImageSize:
            return "Image is too small for feature extraction (minimum 64×64)"
        }
    }
}
