import SwiftUI

/// Bootstrap and device pairing administration page.
///
/// Placeholder — shows informational UI about device pairing and
/// artifact management. These features require the full sync
/// and security subsystems.
struct BootstrapAdminPage: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                Text("Bootstrap Admin")
                    .font(.largeTitle)
                    .fontWeight(.bold)

                GroupBox("Pairing Codes") {
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Generate one-time pairing codes to add new devices to the company network.")
                            .font(.callout)
                            .foregroundStyle(.secondary)

                        HStack {
                            Button("Generate Pairing Code") {}
                                .buttonStyle(.borderedProminent)
                                .disabled(true)
                            Spacer()
                        }

                        Text("No active pairing codes")
                            .foregroundStyle(.tertiary)
                            .padding(.vertical, 4)
                    }
                    .padding(.vertical, 4)
                }

                GroupBox("Registered Devices") {
                    VStack(spacing: 12) {
                        Image(systemName: "desktopcomputer")
                            .font(.system(size: 32))
                            .foregroundStyle(.tertiary)
                        Text("Device management will be available here once sync is configured.")
                            .foregroundStyle(.secondary)
                            .multilineTextAlignment(.center)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 12)
                }

                GroupBox("Artifact Management") {
                    Text("Bootstrap artifacts (initial database snapshots, configuration bundles) will be managed here for new device provisioning.")
                        .font(.callout)
                        .foregroundStyle(.secondary)
                        .padding(.vertical, 4)
                }

                infoCard(
                    "How Device Bootstrap Works",
                    text: "New devices join the company network by entering a one-time pairing code generated by an admin. The pairing process transfers the company database, encryption keys, and configuration to the new device."
                )
            }
            .padding(24)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
    }

    private func infoCard(_ title: String, text: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Label(title, systemImage: "info.circle")
                .font(.headline)
            Text(text)
                .font(.callout)
                .foregroundStyle(.secondary)
        }
        .padding()
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(RoundedRectangle(cornerRadius: 10).fill(Color.blue.opacity(0.05)))
    }
}
