import Foundation
import GRDB

/// Wishlist Service — CRUD for wishlist items that feed into procurement.
///
/// Wishlist items can be manually added or auto-generated by forecasting.
/// Items flow through: pending → approved → sent_to_procurement (or dismissed).
///
/// All queries run against the local SQLite database via GRDB.
/// Tables that may not yet exist are handled gracefully.
public final class WishlistService: Sendable {
    private let db: AppDatabase
    private let auth: AuthService

    public init(db: AppDatabase, auth: AuthService) {
        self.db = db
        self.auth = auth
    }

    // =========================================================================
    // MARK: - Error Types
    // =========================================================================

    public enum WishlistError: LocalizedError, Sendable, Equatable {
        case itemNotFound(Int64)
        case invalidStatus(String)
        case alreadyProcessed(Int64, String)
        case dismissReasonRequired
        case insufficientPermissions(required: String)

        public var errorDescription: String? {
            switch self {
            case .itemNotFound(let id): "Wishlist item #\(id) not found"
            case .invalidStatus(let msg): msg
            case .alreadyProcessed(let id, let status):
                "Wishlist item #\(id) is already \(status)"
            case .dismissReasonRequired:
                "A dismiss reason is required"
            case .insufficientPermissions(let required):
                "You don't have permission to perform this action (required: \(required))"
            }
        }
    }

    // =========================================================================
    // MARK: - Result Types
    // =========================================================================

    /// Counts per status for smart-card display.
    public struct StatusCounts: Sendable {
        public let pending: Int
        public let approved: Int
        public let dismissed: Int
        public let sentToProcurement: Int
        public let total: Int

        public init(pending: Int = 0, approved: Int = 0, dismissed: Int = 0, sentToProcurement: Int = 0) {
            self.pending = pending
            self.approved = approved
            self.dismissed = dismissed
            self.sentToProcurement = sentToProcurement
            self.total = pending + approved + dismissed + sentToProcurement
        }
    }

    // =========================================================================
    // MARK: - List / Query
    // =========================================================================

    /// List wishlist items, optionally filtered by status.
    public func listItems(status: String? = nil) throws -> [WishlistItem] {
        do {
            return try db.writer.read { dbConn in
                var request = WishlistItem
                    .order(Column("created_at").desc)

                if let status = status {
                    request = request.filter(Column("status") == status)
                }

                return try request.fetchAll(dbConn)
            }
        } catch {
            if isTableNotFoundError(error) { return [] }
            throw error
        }
    }

    /// Get a single wishlist item by ID.
    public func getItem(id: Int64) throws -> WishlistItem? {
        do {
            return try db.writer.read { dbConn in
                try WishlistItem.fetchOne(dbConn, key: id)
            }
        } catch {
            if isTableNotFoundError(error) { return nil }
            throw error
        }
    }

    /// Get counts per status for smart-card filters.
    public func getStatusCounts() throws -> StatusCounts {
        do {
            return try db.writer.read { dbConn in
                let rows = try Row.fetchAll(dbConn, sql: """
                    SELECT status, COUNT(*) as cnt
                    FROM wishlist_items
                    GROUP BY status
                """)

                var pending = 0, approved = 0, dismissed = 0, sent = 0
                for row in rows {
                    let status: String = row["status"]
                    let count: Int = row["cnt"]
                    switch status {
                    case "pending": pending = count
                    case "approved": approved = count
                    case "dismissed": dismissed = count
                    case "sent_to_procurement": sent = count
                    default: break
                    }
                }
                return StatusCounts(pending: pending, approved: approved, dismissed: dismissed, sentToProcurement: sent)
            }
        } catch {
            if isTableNotFoundError(error) { return StatusCounts() }
            throw error
        }
    }

    // =========================================================================
    // MARK: - Create
    // =========================================================================

    /// Add a new wishlist item.
    @discardableResult
    public func addItem(
        partId: Int64? = nil,
        partName: String,
        qtySuggested: Int = 1,
        reason: String? = nil,
        priority: String = "normal",
        sourceType: String = "manual",
        requestedBy: String? = nil,
        notes: String? = nil,
        certaintyScore: Double? = nil
    ) throws -> WishlistItem {
        try db.writer.write { dbConn in
            let now = Date()
            let nowString = CoreFormatters.iso8601.string(from: now)
            // Manual items auto-approve after 14 days if no action taken
            let autoApprove: String? = sourceType == "manual"
                ? CoreFormatters.iso8601.string(from: now.addingTimeInterval(14 * 24 * 3600))
                : nil
            var item = WishlistItem(
                id: nil,
                partId: partId,
                partName: partName,
                qtySuggested: qtySuggested,
                reason: reason,
                priority: priority,
                sourceType: sourceType,
                status: "pending",
                requestedBy: requestedBy,
                approvedBy: nil,
                approvedAt: nil,
                dismissedBy: nil,
                dismissedAt: nil,
                dismissReason: nil,
                notes: notes,
                createdAt: nowString,
                updatedAt: nowString,
                autoApproveAt: autoApprove,
                certaintyScore: certaintyScore
            )
            try item.insert(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Update
    // =========================================================================

    /// Update an existing wishlist item's editable fields.
    @discardableResult
    public func updateItem(
        id: Int64,
        partName: String? = nil,
        qtySuggested: Int? = nil,
        reason: String? = nil,
        priority: String? = nil,
        notes: String? = nil
    ) throws -> WishlistItem {
        try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            if let partName = partName { item.partName = partName }
            if let qtySuggested = qtySuggested { item.qtySuggested = qtySuggested }
            if let reason = reason { item.reason = reason }
            if let priority = priority { item.priority = priority }
            if let notes = notes { item.notes = notes }
            try item.update(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Status Transitions
    // =========================================================================

    /// Approve a pending wishlist item.
    /// Requires the caller to hold the `wishlist.approve` permission.
    @discardableResult
    public func approveItem(id: Int64, byUserId: Int64) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.approve") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.approve")
        }
        let displayName = (try? auth.getUser(byUserId))?.displayName ?? "User #\(byUserId)"
        return try _performApprove(id: id, approvedByName: displayName)
    }

    /// Dismiss a pending wishlist item. A reason is required.
    /// Requires the caller to hold the `wishlist.dismiss` permission.
    @discardableResult
    public func dismissItem(id: Int64, byUserId: Int64, reason: String) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.dismiss") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.dismiss")
        }
        let displayName = (try? auth.getUser(byUserId))?.displayName ?? "User #\(byUserId)"
        return try _performDismiss(id: id, dismissedByName: displayName, reason: reason)
    }

    /// Mark an approved item as sent to procurement.
    /// Requires the caller to hold the `wishlist.send_to_procurement` permission.
    @discardableResult
    public func sendToProcurement(id: Int64, byUserId: Int64) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.send_to_procurement") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.send_to_procurement")
        }
        return try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "approved" else {
                throw WishlistError.invalidStatus(
                    "Only approved items can be sent to procurement (current: \(item.status))"
                )
            }
            item.status = "sent_to_procurement"
            try item.update(dbConn)
            return item
        }
    }

    /// Reopen a dismissed item back to pending.
    /// Requires the caller to hold the `wishlist.reopen` permission.
    @discardableResult
    public func reopenItem(id: Int64, byUserId: Int64) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.reopen") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.reopen")
        }
        return try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "dismissed" else {
                throw WishlistError.invalidStatus(
                    "Only dismissed items can be reopened (current: \(item.status))"
                )
            }
            item.status = "pending"
            item.dismissedBy = nil
            item.dismissedAt = nil
            try item.update(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Internal State-Mutation Helpers (no permission check)
    // =========================================================================

    /// Internal approve — called by `processAutoApprovals` (system path, no user permission check).
    @discardableResult
    private func _performApprove(id: Int64, approvedByName: String) throws -> WishlistItem {
        try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "pending" else {
                throw WishlistError.alreadyProcessed(id, item.status)
            }
            item.status = "approved"
            item.approvedBy = approvedByName
            item.approvedAt = Self.nowString()
            try item.update(dbConn)
            return item
        }
    }

    /// Internal dismiss — called by system paths that bypass the permission gate.
    @discardableResult
    private func _performDismiss(id: Int64, dismissedByName: String, reason: String) throws -> WishlistItem {
        guard !reason.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw WishlistError.dismissReasonRequired
        }
        return try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "pending" || item.status == "approved" else {
                throw WishlistError.alreadyProcessed(id, item.status)
            }
            item.status = "dismissed"
            item.dismissedBy = dismissedByName
            item.dismissedAt = Self.nowString()
            item.dismissReason = reason.trimmingCharacters(in: .whitespacesAndNewlines)
            try item.update(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Delete
    // =========================================================================

    /// Permanently delete a wishlist item.
    public func deleteItem(id: Int64) throws {
        try db.writer.write { dbConn in
            guard let item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            try item.delete(dbConn)
        }
    }

    // =========================================================================
    // MARK: - Sectioned Items & Auto-Approvals
    // =========================================================================

    /// Items grouped by source type for the 3-section UI layout.
    public struct WishlistSections: Sendable {
        public let userAdded: [WishlistItem]       // source_type = "manual"
        public let forecastDemand: [WishlistItem]  // source_type = "forecast"
        public let autoAdded: [WishlistItem]       // source_type = "system"

        public init(userAdded: [WishlistItem] = [], forecastDemand: [WishlistItem] = [], autoAdded: [WishlistItem] = []) {
            self.userAdded = userAdded
            self.forecastDemand = forecastDemand
            self.autoAdded = autoAdded
        }
    }

    /// Returns wishlist items split into 3 sections by source_type.
    /// Fetches wishlist items grouped into three sections: User Added, Forecast Demand, System Auto-Added.
    /// Call `processAutoApprovals(by:)` before this method (in a background task) to keep auto-approval state current.
    public func getSectionedItems(statusFilter: String? = nil) throws -> WishlistSections {
        return try db.writer.read { dbConn in
            var base = WishlistItem
                .order(Column("created_at").desc)

            if let statusFilter = statusFilter {
                base = base.filter(Column("status") == statusFilter)
            }

            let all = try base.fetchAll(dbConn)

            let userAdded = all.filter { $0.sourceType == "manual" }
            let forecastDemand = all.filter { $0.sourceType == "forecast" }
            let autoAdded = all.filter { $0.sourceType != "manual" && $0.sourceType != "forecast" }

            return WishlistSections(userAdded: userAdded, forecastDemand: forecastDemand, autoAdded: autoAdded)
        }
    }

    /// Auto-approve any pending manual items whose auto_approve_at has passed.
    /// Returns the count of items that were auto-approved.
    @discardableResult
    public func processAutoApprovals(by approver: String) throws -> Int {
        do {
            let now = Self.nowString()
            let expiredItems = try db.writer.read { dbConn in
                try WishlistItem
                    .filter(Column("status") == "pending")
                    .filter(Column("auto_approve_at") != nil)
                    .filter(Column("auto_approve_at") <= now)
                    .fetchAll(dbConn)
            }

            var count = 0
            for item in expiredItems {
                guard let id = item.id else { continue }
                _ = try _performApprove(id: id, approvedByName: approver)
                count += 1
            }
            return count
        } catch {
            if isTableNotFoundError(error) { return 0 }
            throw error
        }
    }

    // =========================================================================
    // MARK: - Helpers
    // =========================================================================

    private static func nowString() -> String { CoreFormatters.nowISO() }

    private func isTableNotFoundError(_ error: Error) -> Bool {
        let message = String(describing: error)
        return message.contains("no such table") || message.contains("no such column")
    }
}
