import Foundation
import GRDB

/// Wishlist Service — CRUD for wishlist items that feed into procurement.
///
/// Wishlist items can be manually added or auto-generated by forecasting.
/// Items flow through: pending → approved → sent_to_procurement (or dismissed).
///
/// All queries run against the local SQLite database via GRDB.
/// Tables that may not yet exist are handled gracefully.
public final class WishlistService: Sendable {
    private let db: AppDatabase
    private let auth: AuthService

    public init(db: AppDatabase, auth: AuthService) {
        self.db = db
        self.auth = auth
    }

    // =========================================================================
    // MARK: - Error Types
    // =========================================================================

    public enum WishlistError: LocalizedError, Sendable, Equatable {
        case itemNotFound(Int64)
        case invalidStatus(String)
        case alreadyProcessed(Int64, String)
        case dismissReasonRequired
        case insufficientPermissions(required: String)

        public var errorDescription: String? {
            switch self {
            case .itemNotFound(let id): "Wishlist item #\(id) not found"
            case .invalidStatus(let msg): msg
            case .alreadyProcessed(let id, let status):
                "Wishlist item #\(id) is already \(status)"
            case .dismissReasonRequired:
                "A dismiss reason is required"
            case .insufficientPermissions(let required):
                "You don't have permission to perform this action (required: \(required))"
            }
        }
    }

    // =========================================================================
    // MARK: - Result Types
    // =========================================================================

    /// Counts per status for smart-card display.
    public struct StatusCounts: Sendable {
        public let pending: Int
        public let approved: Int
        public let dismissed: Int
        public let sentToProcurement: Int
        public let total: Int

        public init(pending: Int = 0, approved: Int = 0, dismissed: Int = 0, sentToProcurement: Int = 0) {
            self.pending = pending
            self.approved = approved
            self.dismissed = dismissed
            self.sentToProcurement = sentToProcurement
            self.total = pending + approved + dismissed + sentToProcurement
        }
    }

    /// Deterministic outcome for a below-MIN stock candidate.
    public enum BelowMinRouteAction: String, Sendable, Codable, Equatable {
        case shopMovement = "shop_movement"
        case wishlistPending = "wishlist_pending"
        case wishlistApproved = "wishlist_approved"
        case physicalAudit = "physical_audit"
    }

    /// A below-MIN route decision produced by the automation scan.
    public struct BelowMinRouteDecision: Sendable, Equatable {
        public let partId: Int64
        public let partName: String
        public let locationType: String
        public let locationId: Int64
        public let currentQty: Int
        public let minStock: Int
        public let targetStock: Int
        public let suggestedQty: Int
        public let certaintyScore: Double
        public let action: BelowMinRouteAction
        public let wishlistItemId: Int64?
        public let reason: String

        public init(
            partId: Int64,
            partName: String,
            locationType: String,
            locationId: Int64,
            currentQty: Int,
            minStock: Int,
            targetStock: Int,
            suggestedQty: Int,
            certaintyScore: Double,
            action: BelowMinRouteAction,
            wishlistItemId: Int64?,
            reason: String
        ) {
            self.partId = partId
            self.partName = partName
            self.locationType = locationType
            self.locationId = locationId
            self.currentQty = currentQty
            self.minStock = minStock
            self.targetStock = targetStock
            self.suggestedQty = suggestedQty
            self.certaintyScore = certaintyScore
            self.action = action
            self.wishlistItemId = wishlistItemId
            self.reason = reason
        }
    }

    // =========================================================================
    // MARK: - List / Query
    // =========================================================================

    /// List wishlist items, optionally filtered by status.
    public func listItems(status: String? = nil) throws -> [WishlistItem] {
        do {
            return try db.writer.read { dbConn in
                var request = WishlistItem
                    .order(Column("created_at").desc)

                if let status = status {
                    request = request.filter(Column("status") == status)
                }

                return try request.fetchAll(dbConn)
            }
        } catch {
            if isTableNotFoundError(error) { return [] }
            throw error
        }
    }

    /// Get a single wishlist item by ID.
    public func getItem(id: Int64) throws -> WishlistItem? {
        do {
            return try db.writer.read { dbConn in
                try WishlistItem.fetchOne(dbConn, key: id)
            }
        } catch {
            if isTableNotFoundError(error) { return nil }
            throw error
        }
    }

    /// Get counts per status for smart-card filters.
    public func getStatusCounts() throws -> StatusCounts {
        do {
            return try db.writer.read { dbConn in
                let rows = try Row.fetchAll(dbConn, sql: """
                    SELECT status, COUNT(*) as cnt
                    FROM wishlist_items
                    GROUP BY status
                """)

                var pending = 0, approved = 0, dismissed = 0, sent = 0
                for row in rows {
                    let status: String = row["status"]
                    let count: Int = row["cnt"]
                    switch status {
                    case "pending": pending = count
                    case "approved": approved = count
                    case "dismissed": dismissed = count
                    case "sent_to_procurement": sent = count
                    default: break
                    }
                }
                return StatusCounts(pending: pending, approved: approved, dismissed: dismissed, sentToProcurement: sent)
            }
        } catch {
            if isTableNotFoundError(error) { return StatusCounts() }
            throw error
        }
    }

    // =========================================================================
    // MARK: - Create
    // =========================================================================

    /// Add a new wishlist item.
    @discardableResult
    public func addItem(
        partId: Int64? = nil,
        partName: String,
        qtySuggested: Int = 1,
        reason: String? = nil,
        priority: String = "normal",
        sourceType: String = "manual",
        requestedBy: String? = nil,
        notes: String? = nil,
        certaintyScore: Double? = nil,
        locationType: String? = nil,
        locationId: Int64? = nil
    ) throws -> WishlistItem {
        try db.writer.write { dbConn in
            let now = Date()
            let nowString = CoreFormatters.iso8601.string(from: now)
            // Manual items auto-approve after 14 days if no action taken
            let autoApprove: String? = sourceType == "manual"
                ? CoreFormatters.iso8601.string(from: now.addingTimeInterval(14 * 24 * 3600))
                : nil
            var item = WishlistItem(
                id: nil,
                partId: partId,
                partName: partName,
                qtySuggested: qtySuggested,
                reason: reason,
                priority: priority,
                sourceType: sourceType,
                status: "pending",
                requestedBy: requestedBy,
                approvedBy: nil,
                approvedAt: nil,
                dismissedBy: nil,
                dismissedAt: nil,
                dismissReason: nil,
                notes: notes,
                createdAt: nowString,
                updatedAt: nowString,
                autoApproveAt: autoApprove,
                certaintyScore: certaintyScore,
                locationType: locationType,
                locationId: locationId
            )
            try item.insert(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Below-MIN Automation
    // =========================================================================

    /// Generate deterministic below-MIN routes for location-aware stock targets.
    ///
    /// The scan follows the shop-check-first policy:
    /// 1. If the target location is low-confidence, route to physical audit.
    /// 2. For non-shop locations, use spare shop stock before procurement.
    /// 3. If procurement is needed, create or update one system wishlist item
    ///    scoped to the part+location; high-certainty items are auto-approved.
    @discardableResult
    public func generateBelowMinWishlistRoutes(
        locationType: String? = nil,
        locationId: Int64? = nil,
        shopLocationType: String = "warehouse",
        shopLocationId: Int64 = 1,
        auditCertaintyThreshold: Double = 0.5,
        autoApproveCertaintyThreshold: Double = 0.8
    ) throws -> [BelowMinRouteDecision] {
        try db.writer.write { dbConn in
            var whereClauses = [
                "lst.deleted_at IS NULL",
                "COALESCE(lst.do_not_restock, 0) = 0",
                "lst.min_stock > 0",
                "p.deleted_at IS NULL",
                "COALESCE(p.is_active, 1) = 1",
                "COALESCE(p.auto_add_to_wishlist, 0) = 1"
            ]
            var args: [DatabaseValueConvertible?] = []

            if let locationType {
                whereClauses.append("lst.location_type = ?")
                args.append(locationType)
            }
            if let locationId {
                whereClauses.append("lst.location_id = ?")
                args.append(locationId)
            }

            let candidates = try Row.fetchAll(dbConn, sql: """
                SELECT lst.part_id,
                       p.name AS part_name,
                       lst.location_type,
                       lst.location_id,
                       lst.min_stock,
                       CASE
                           WHEN COALESCE(lst.target_stock, 0) > lst.min_stock
                           THEN lst.target_stock
                           ELSE lst.min_stock
                       END AS target_stock,
                       COALESCE(lst.certainty_rating, 0) AS certainty_score,
                       COALESCE(SUM(s.qty), 0) AS current_qty
                FROM location_stock_targets lst
                JOIN parts p ON p.id = lst.part_id
                LEFT JOIN stock s ON s.part_id = lst.part_id
                    AND s.location_type = lst.location_type
                    AND s.location_id = lst.location_id
                    AND s.deleted_at IS NULL
                WHERE \(whereClauses.joined(separator: " AND "))
                GROUP BY lst.part_id, lst.location_type, lst.location_id
                HAVING current_qty < lst.min_stock
                ORDER BY (lst.min_stock - current_qty) DESC, p.name ASC
                """, arguments: StatementArguments(args))

            var decisions: [BelowMinRouteDecision] = []

            for row in candidates {
                let partId: Int64 = row["part_id"]
                let partName: String = row["part_name"] ?? "Unknown Part"
                let targetLocationType: String = row["location_type"] ?? "warehouse"
                let targetLocationId: Int64 = row["location_id"] ?? 1
                let currentQty: Int = row["current_qty"] ?? 0
                let minStock: Int = row["min_stock"] ?? 0
                let targetStock: Int = row["target_stock"] ?? minStock
                let certaintyScore: Double = row["certainty_score"] ?? 0
                let suggestedQty = max(1, targetStock - currentQty)

                if certaintyScore < auditCertaintyThreshold {
                    decisions.append(BelowMinRouteDecision(
                        partId: partId,
                        partName: partName,
                        locationType: targetLocationType,
                        locationId: targetLocationId,
                        currentQty: currentQty,
                        minStock: minStock,
                        targetStock: targetStock,
                        suggestedQty: suggestedQty,
                        certaintyScore: certaintyScore,
                        action: .physicalAudit,
                        wishlistItemId: nil,
                        reason: "Below MIN but stock certainty is too low for procurement; route to physical audit first."
                    ))
                    continue
                }

                if targetLocationType != shopLocationType || targetLocationId != shopLocationId {
                    let shopSpareQty = try Self.spareShopQty(
                        dbConn,
                        partId: partId,
                        shopLocationType: shopLocationType,
                        shopLocationId: shopLocationId
                    )
                    if shopSpareQty > 0 {
                        decisions.append(BelowMinRouteDecision(
                            partId: partId,
                            partName: partName,
                            locationType: targetLocationType,
                            locationId: targetLocationId,
                            currentQty: currentQty,
                            minStock: minStock,
                            targetStock: targetStock,
                            suggestedQty: min(suggestedQty, shopSpareQty),
                            certaintyScore: certaintyScore,
                            action: .shopMovement,
                            wishlistItemId: nil,
                            reason: "Below MIN and shop has spare stock; move stock from shop before ordering."
                        ))
                        continue
                    }
                }

                let shouldApprove = certaintyScore >= autoApproveCertaintyThreshold
                let item = try Self.upsertBelowMinWishlistItem(
                    dbConn,
                    partId: partId,
                    partName: partName,
                    qtySuggested: suggestedQty,
                    locationType: targetLocationType,
                    locationId: targetLocationId,
                    certaintyScore: certaintyScore,
                    approve: shouldApprove
                )

                decisions.append(BelowMinRouteDecision(
                    partId: partId,
                    partName: partName,
                    locationType: targetLocationType,
                    locationId: targetLocationId,
                    currentQty: currentQty,
                    minStock: minStock,
                    targetStock: targetStock,
                    suggestedQty: suggestedQty,
                    certaintyScore: certaintyScore,
                    action: shouldApprove ? .wishlistApproved : .wishlistPending,
                    wishlistItemId: item.id,
                    reason: shouldApprove
                        ? "Below MIN, shop has no spare stock, and certainty is high enough to approve procurement demand."
                        : "Below MIN, shop has no spare stock; create pending procurement demand for review."
                ))
            }

            return decisions
        }
    }

    // =========================================================================
    // MARK: - Update
    // =========================================================================

    /// Update an existing wishlist item's editable fields.
    @discardableResult
    public func updateItem(
        id: Int64,
        partName: String? = nil,
        qtySuggested: Int? = nil,
        reason: String? = nil,
        priority: String? = nil,
        notes: String? = nil
    ) throws -> WishlistItem {
        try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            if let partName = partName { item.partName = partName }
            if let qtySuggested = qtySuggested { item.qtySuggested = qtySuggested }
            if let reason = reason { item.reason = reason }
            if let priority = priority { item.priority = priority }
            if let notes = notes { item.notes = notes }
            try item.update(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Status Transitions
    // =========================================================================

    /// Approve a pending wishlist item.
    /// Requires the caller to hold the `wishlist.approve` permission.
    @discardableResult
    public func approveItem(id: Int64, byUserId: Int64) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.approve") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.approve")
        }
        guard let userRecord = try auth.getUser(byUserId) else {
            throw WishlistError.insufficientPermissions(required: "wishlist.approve")
        }
        return try _performApprove(id: id, approvedByName: userRecord.displayName)
    }

    /// Dismiss a pending wishlist item. A reason is required.
    /// Requires the caller to hold the `wishlist.dismiss` permission.
    @discardableResult
    public func dismissItem(id: Int64, byUserId: Int64, reason: String) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.dismiss") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.dismiss")
        }
        guard let userRecord = try auth.getUser(byUserId) else {
            throw WishlistError.insufficientPermissions(required: "wishlist.dismiss")
        }
        return try _performDismiss(id: id, dismissedByName: userRecord.displayName, reason: reason)
    }

    /// Mark an approved item as sent to procurement.
    /// Requires the caller to hold the `wishlist.send_to_procurement` permission.
    @discardableResult
    public func sendToProcurement(id: Int64, byUserId: Int64) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.send_to_procurement") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.send_to_procurement")
        }
        return try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "approved" else {
                throw WishlistError.invalidStatus(
                    "Only approved items can be sent to procurement (current: \(item.status))"
                )
            }
            item.status = "sent_to_procurement"
            try item.update(dbConn)
            return item
        }
    }

    /// Reopen a dismissed item back to pending.
    /// Requires the caller to hold the `wishlist.reopen` permission.
    @discardableResult
    public func reopenItem(id: Int64, byUserId: Int64) throws -> WishlistItem {
        guard try auth.hasPermission(byUserId, permissionKey: "wishlist.reopen") else {
            throw WishlistError.insufficientPermissions(required: "wishlist.reopen")
        }
        return try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "dismissed" else {
                throw WishlistError.invalidStatus(
                    "Only dismissed items can be reopened (current: \(item.status))"
                )
            }
            item.status = "pending"
            item.dismissedBy = nil
            item.dismissedAt = nil
            try item.update(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Internal State-Mutation Helpers (no permission check)
    // =========================================================================

    /// Internal approve — called by `processAutoApprovals` (system or permissioned path).
    @discardableResult
    private func _performApprove(id: Int64, approvedByName: String) throws -> WishlistItem {
        try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "pending" else {
                throw WishlistError.alreadyProcessed(id, item.status)
            }
            item.status = "approved"
            item.approvedBy = approvedByName
            item.approvedAt = Self.nowString()
            try item.update(dbConn)
            return item
        }
    }

    /// Internal dismiss — called by system paths that bypass the permission gate.
    @discardableResult
    private func _performDismiss(id: Int64, dismissedByName: String, reason: String) throws -> WishlistItem {
        guard !reason.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw WishlistError.dismissReasonRequired
        }
        return try db.writer.write { dbConn in
            guard var item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            guard item.status == "pending" || item.status == "approved" else {
                throw WishlistError.alreadyProcessed(id, item.status)
            }
            item.status = "dismissed"
            item.dismissedBy = dismissedByName
            item.dismissedAt = Self.nowString()
            item.dismissReason = reason.trimmingCharacters(in: .whitespacesAndNewlines)
            try item.update(dbConn)
            return item
        }
    }

    // =========================================================================
    // MARK: - Delete
    // =========================================================================

    /// Permanently delete a wishlist item.
    public func deleteItem(id: Int64) throws {
        try db.writer.write { dbConn in
            guard let item = try WishlistItem.fetchOne(dbConn, key: id) else {
                throw WishlistError.itemNotFound(id)
            }
            try item.delete(dbConn)
        }
    }

    // =========================================================================
    // MARK: - Sectioned Items & Auto-Approvals
    // =========================================================================

    /// Items grouped by source type for the 3-section UI layout.
    public struct WishlistSections: Sendable {
        public let userAdded: [WishlistItem]       // source_type = "manual"
        public let forecastDemand: [WishlistItem]  // source_type = "forecast"
        public let autoAdded: [WishlistItem]       // source_type = "system"

        public init(userAdded: [WishlistItem] = [], forecastDemand: [WishlistItem] = [], autoAdded: [WishlistItem] = []) {
            self.userAdded = userAdded
            self.forecastDemand = forecastDemand
            self.autoAdded = autoAdded
        }
    }

    /// Returns wishlist items split into 3 sections by source_type.
    /// Fetches wishlist items grouped into three sections: User Added, Forecast Demand, System Auto-Added.
    /// Call `processAutoApprovals(byUserId:)` before this method (in a background task) to keep auto-approval state current.
    public func getSectionedItems(statusFilter: String? = nil) throws -> WishlistSections {
        return try db.writer.read { dbConn in
            var base = WishlistItem
                .order(Column("created_at").desc)

            if let statusFilter = statusFilter {
                base = base.filter(Column("status") == statusFilter)
            }

            let all = try base.fetchAll(dbConn)

            let userAdded = all.filter { $0.sourceType == "manual" }
            let forecastDemand = all.filter { $0.sourceType == "forecast" }
            let autoAdded = all.filter { $0.sourceType != "manual" && $0.sourceType != "forecast" }

            return WishlistSections(userAdded: userAdded, forecastDemand: forecastDemand, autoAdded: autoAdded)
        }
    }

    /// Auto-approve any pending items whose auto_approve_at has passed.
    ///
    /// - Parameter byUserId: The ID of the user triggering auto-approval. When non-nil, the caller
    ///   must hold the `wishlist.auto_approve` permission; otherwise
    ///   `WishlistError.insufficientPermissions` is thrown. When nil (background/system path)
    ///   the approval is attributed to `"System (Auto)"` with no permission check.
    ///
    /// - Returns: The count of items that were auto-approved.
    @discardableResult
    public func processAutoApprovals(byUserId: Int64?) throws -> Int {
        let approverName: String
        if let userId = byUserId {
            guard try auth.hasPermission(userId, permissionKey: "wishlist.auto_approve") else {
                throw WishlistError.insufficientPermissions(required: "wishlist.auto_approve")
            }
            guard let userRecord = try auth.getUser(userId) else {
                throw WishlistError.insufficientPermissions(required: "wishlist.auto_approve")
            }
            approverName = userRecord.displayName
        } else {
            approverName = "System (Auto)"
        }

        do {
            let now = Self.nowString()
            let expiredItems = try db.writer.read { dbConn in
                try WishlistItem
                    .filter(Column("status") == "pending")
                    .filter(Column("auto_approve_at") != nil)
                    .filter(Column("auto_approve_at") <= now)
                    .fetchAll(dbConn)
            }

            var count = 0
            for item in expiredItems {
                guard let id = item.id else { continue }
                _ = try _performApprove(id: id, approvedByName: approverName)
                count += 1
            }
            return count
        } catch {
            if isTableNotFoundError(error) { return 0 }
            throw error
        }
    }

    // =========================================================================
    // MARK: - Helpers
    // =========================================================================

    private static func nowString() -> String { CoreFormatters.nowISO() }

    private static func spareShopQty(
        _ dbConn: Database,
        partId: Int64,
        shopLocationType: String,
        shopLocationId: Int64
    ) throws -> Int {
        let shopCurrent = try Int.fetchOne(dbConn, sql: """
            SELECT COALESCE(SUM(qty), 0)
            FROM stock
            WHERE part_id = ? AND location_type = ? AND location_id = ?
              AND deleted_at IS NULL
            """, arguments: [partId, shopLocationType, shopLocationId]) ?? 0

        let shopMin = try Int.fetchOne(dbConn, sql: """
            SELECT COALESCE(lst.min_stock, p.min_stock_level, 0)
            FROM parts p
            LEFT JOIN location_stock_targets lst ON lst.part_id = p.id
                AND lst.location_type = ? AND lst.location_id = ?
                AND lst.deleted_at IS NULL
            WHERE p.id = ? AND p.deleted_at IS NULL
            """, arguments: [shopLocationType, shopLocationId, partId]) ?? 0

        return max(0, shopCurrent - shopMin)
    }

    private static func upsertBelowMinWishlistItem(
        _ dbConn: Database,
        partId: Int64,
        partName: String,
        qtySuggested: Int,
        locationType: String,
        locationId: Int64,
        certaintyScore: Double,
        approve: Bool
    ) throws -> WishlistItem {
        let now = nowString()
        let status = approve ? "approved" : "pending"
        let approvedBy = approve ? "System (Below-MIN)" : nil
        let approvedAt = approve ? now : nil
        let reason = "Auto-created: \(locationType) #\(locationId) is below MIN and shop has no spare stock."

        if let existingId = try Int64.fetchOne(dbConn, sql: """
            SELECT id
            FROM wishlist_items
            WHERE part_id = ?
              AND location_type = ?
              AND location_id = ?
              AND source_type = 'system'
              AND status IN ('pending', 'approved')
            ORDER BY created_at DESC
            LIMIT 1
            """, arguments: [partId, locationType, locationId]),
           var existing = try WishlistItem.fetchOne(dbConn, key: existingId) {
            existing.partName = partName
            existing.qtySuggested = qtySuggested
            existing.reason = reason
            existing.priority = "high"
            existing.certaintyScore = certaintyScore
            existing.locationType = locationType
            existing.locationId = locationId
            existing.updatedAt = now
            if approve && existing.status == "pending" {
                existing.status = status
                existing.approvedBy = approvedBy
                existing.approvedAt = approvedAt
            }
            try existing.update(dbConn)
            return existing
        }

        var item = WishlistItem(
            id: nil,
            partId: partId,
            partName: partName,
            qtySuggested: qtySuggested,
            reason: reason,
            priority: "high",
            sourceType: "system",
            status: status,
            requestedBy: "System (Below-MIN)",
            approvedBy: approvedBy,
            approvedAt: approvedAt,
            dismissedBy: nil,
            dismissedAt: nil,
            dismissReason: nil,
            notes: "Generated by below-MIN automation after shop-stock check.",
            createdAt: now,
            updatedAt: now,
            autoApproveAt: nil,
            certaintyScore: certaintyScore,
            locationType: locationType,
            locationId: locationId
        )
        try item.insert(dbConn)
        return item
    }

    private func isTableNotFoundError(_ error: Error) -> Bool {
        let message = String(describing: error)
        return message.contains("no such table") || message.contains("no such column")
    }
}
