import XCTest

final class WarehouseStickerProgressScopeRegressionTests: XCTestCase {
    func testStickerChecklistProgressUsesScopedKeyInsteadOfFloorPlanOnlyKey() throws {
        let source = try Self.readSource("WarehouseWizardStep3.swift")

        XCTAssertTrue(
            source.contains("wizard_checked_stickers_v2"),
            "Sticker progress should use the v2 scoped key namespace."
        )
        XCTAssertTrue(
            source.contains("scopedStickerProgressKey"),
            "Sticker progress should be generated by an explicit scoped key helper."
        )
        XCTAssertTrue(
            source.contains("getBusinessProfile"),
            "Sticker progress should include active company/profile scope so profile resets do not inherit stale progress."
        )
        XCTAssertTrue(
            source.contains("appCore.currentUser"),
            "Sticker progress should include the active user scope."
        )
        XCTAssertTrue(
            source.contains("fullLocationCode") && source.contains("deterministicSignature"),
            "Sticker progress should include the generated sticker set/setup signature."
        )
        XCTAssertTrue(
            source.contains("removeObject(forKey: legacyStickerProgressKey)"),
            "The old floorPlanId-only key should be purged instead of used as a fallback."
        )
        XCTAssertFalse(
            source.contains("UserDefaults.standard.array(\n                forKey: \"wizard_checked_stickers_\\(floorPlanId)\""),
            "Loading from the old floorPlanId-only key would reintroduce stale sticker progress."
        )
        XCTAssertFalse(
            source.contains("UserDefaults.standard.set(\n            Array(checkedStickers),\n            forKey: \"wizard_checked_stickers_\\(floorPlanId)\""),
            "Writing to the old floorPlanId-only key would reintroduce cross-reset/profile leakage."
        )
    }

    private static func readSource(_ fileName: String) throws -> String {
        let root = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
        let url = root
            .appendingPathComponent("Weird Parts IOS")
            .appendingPathComponent("Features")
            .appendingPathComponent("Warehouse")
            .appendingPathComponent(fileName)
        return try String(contentsOf: url, encoding: .utf8)
    }
}
