import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

// Register the service worker generated by vite-plugin-pwa.
// Skip on Tauri — service workers don't work with the tauri:// scheme.
if ('serviceWorker' in navigator && !('__TAURI__' in window)) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // SW registration failed — non-critical, app works without it
    });
  });
}

// Guard against duplicate createRoot calls during HMR
const container = document.getElementById('root')!;
if (!(container as any)._reactRoot) {
  const root = createRoot(container);
  (container as any)._reactRoot = root;
  root.render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
} else {
  (container as any)._reactRoot.render(
    <StrictMode>
      <App />
    </StrictMode>,
  );
}
