import Foundation
import GRDB

// MARK: - Wishlist Item

/// A wishlist item representing a part that should be procured.
/// Items can be manually added or auto-generated by forecasting.
public struct WishlistItem: Codable, FetchableRecord, MutablePersistableRecord, Identifiable, Sendable {
    public var id: Int64?
    public var partId: Int64?
    public var partName: String
    public var qtySuggested: Int
    public var reason: String?
    public var priority: String
    public var sourceType: String
    public var status: String
    public var requestedBy: String?
    public var approvedBy: String?
    public var approvedAt: String?
    public var dismissedBy: String?
    public var dismissedAt: String?
    public var dismissReason: String?
    public var notes: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var autoApproveAt: String?
    public var certaintyScore: Double?
    public var locationType: String?
    public var locationId: Int64?

    public static let databaseTableName = "wishlist_items"

    enum CodingKeys: String, CodingKey {
        case id, reason, priority, status, notes
        case partId = "part_id"
        case partName = "part_name"
        case qtySuggested = "qty_suggested"
        case sourceType = "source_type"
        case requestedBy = "requested_by"
        case approvedBy = "approved_by"
        case approvedAt = "approved_at"
        case dismissedBy = "dismissed_by"
        case dismissedAt = "dismissed_at"
        case dismissReason = "dismiss_reason"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case autoApproveAt = "auto_approve_at"
        case certaintyScore = "certainty_score"
        case locationType = "location_type"
        case locationId = "location_id"
    }

    public mutating func didInsert(_ inserted: InsertionSuccess) {
        id = inserted.rowID
    }
}
