import SwiftUI
import WiredPartCore

/// Wishlist page for iOS.
///
/// Displays wishlist items that feed into procurement. Items can be manually
/// added or auto-generated by forecasting. Supports status filtering via
/// smart cards, swipe actions for approve/dismiss, pull-to-refresh, and search.
struct IOSWishlistPage: View {
    @EnvironmentObject private var appCore: AppCore

    // MARK: - State

    @State private var allItems: [WishlistItem] = []
    @State private var isLoading = true
    @State private var searchText = ""
    @State private var statusFilter: String? = nil  // nil = all
    @State private var loadError: String?
    @State private var activeSheet: ActiveSheet?

    private enum ActiveSheet: Identifiable {
        case addItem
        case help
        var id: String { String(describing: self) }
    }

    var body: some View {
        VStack(spacing: 0) {
            OnboardingBanner(pageId: "orders-wishlist")
            smartCardFilters
            wishlistList
        }
        .task { appCore.onboardingManager?.markCompleted("wishlist-view") }
        .navigationTitle("Wishlist")
        .searchable(text: $searchText, prompt: "Search wishlist...")
        .toolbar {
            ToolbarItem(placement: .primaryAction) {
                Button { activeSheet = .addItem } label: { Image(systemName: "plus") }
            }
            ToolbarItem(placement: .primaryAction) {
                Button { activeSheet = .help } label: {
                    Image(systemName: "questionmark.circle")
                }
            }
        }
        .sheet(item: $activeSheet) { sheet in
            switch sheet {
            case .addItem:
                AddWishlistItemSheet(onSave: { loadData() })
                    .environmentObject(appCore)
            case .help:
                PageHelpSheet(
                    title: "Wishlist Help",
                    sections: [
                        ("What This Page Does", "Tracks parts that should be procured. Items can be added manually or generated automatically by forecasting when stock levels need attention. Each item has a priority, suggested quantity, and status."),
                        ("How to Use It", "Use the filter cards to view by status (Pending, Approved, Dismissed). Tap + to add a new item. Swipe right to approve a pending item, swipe left to dismiss it. Pull down to refresh."),
                        ("Item Flow", "Pending (needs review) -> Approved (ready for procurement) -> Sent to Procurement (handed off to PO creation). Dismissed items can be reopened if needed."),
                        ("Priority Levels", "Urgent (red) = needs immediate attention. High (orange) = important but not critical. Normal (blue) = standard priority. Low (gray) = nice to have."),
                        ("Tips", "Items from forecasting show their source as 'forecast' with an auto-generated reason. Manual items let you describe why the part is needed. Approved items can be sent to procurement in bulk.")
                    ]
                )
            }
        }
        .onChange(of: searchText) { loadData() }
        .refreshable { loadData() }
        .task { loadData() }
    }

    // MARK: - Smart Card Filters

    private func countForStatus(_ status: String) -> Int {
        allItems.filter { $0.status == status }.count
    }

    private var smartCardFilters: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 8) {
                smartCard("All", count: allItems.count, icon: "heart.text.clipboard", filter: nil, color: Color.accentColor)
                smartCard("Pending", count: countForStatus("pending"), icon: "clock", filter: "pending", color: .orange)
                smartCard("Approved", count: countForStatus("approved"), icon: "checkmark.circle", filter: "approved", color: .green)
                smartCard("Dismissed", count: countForStatus("dismissed"), icon: "xmark.circle", filter: "dismissed", color: .secondary)
                smartCard("Procured", count: countForStatus("sent_to_procurement"), icon: "shippingbox", filter: "sent_to_procurement", color: .purple)
            }
            .padding(.horizontal)
            .padding(.vertical, 8)
        }
    }

    private func smartCard(_ label: String, count: Int, icon: String, filter: String?, color: Color) -> some View {
        Button {
            withAnimation { statusFilter = statusFilter == filter ? nil : filter }
        } label: {
            VStack(spacing: 4) {
                HStack(spacing: 4) {
                    Image(systemName: icon)
                        .font(.caption)
                    Text("\(count)")
                        .font(.title3)
                        .fontWeight(.bold)
                }
                Text(label)
                    .font(.caption2)
            }
            .frame(minWidth: 70)
            .padding(.horizontal, 12)
            .padding(.vertical, 8)
            .background(
                RoundedRectangle(cornerRadius: 10)
                    .fill(statusFilter == filter ? color : Color.secondary.opacity(0.12))
            )
            .foregroundStyle(statusFilter == filter ? .white : .primary)
        }
        .buttonStyle(.plain)
    }

    // MARK: - Wishlist List

    @ViewBuilder
    private var wishlistList: some View {
        if isLoading {
            ProgressView("Loading wishlist...")
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        } else if let error = loadError {
            ErrorStateView(message: error) { loadData() }
        } else if filteredItems.isEmpty {
            EmptyStateView(
                icon: "heart.text.clipboard",
                title: "No Wishlist Items",
                message: searchText.isEmpty
                    ? (statusFilter != nil ? "No items match the selected filter." : "Add parts to your wishlist to track procurement needs.")
                    : "No items match your search."
            )
        } else {
            List {
                ForEach(filteredItems) { item in
                    wishlistRow(item)
                        .swipeActions(edge: .leading, allowsFullSwipe: true) {
                            if item.status == "pending" {
                                Button {
                                    approveItem(item)
                                } label: {
                                    Label("Approve", systemImage: "checkmark.circle")
                                }
                                .tint(.green)
                            }
                            if item.status == "approved" {
                                Button {
                                    sendToProcurement(item)
                                } label: {
                                    Label("Send to PO", systemImage: "shippingbox")
                                }
                                .tint(.purple)
                            }
                        }
                        .swipeActions(edge: .trailing, allowsFullSwipe: true) {
                            if item.status == "pending" || item.status == "approved" {
                                Button(role: .destructive) {
                                    dismissItem(item)
                                } label: {
                                    Label("Dismiss", systemImage: "xmark.circle")
                                }
                            }
                            if item.status == "dismissed" {
                                Button {
                                    reopenItem(item)
                                } label: {
                                    Label("Reopen", systemImage: "arrow.uturn.left")
                                }
                                .tint(.blue)
                            }
                            Button(role: .destructive) {
                                deleteItem(item)
                            } label: {
                                Label("Delete", systemImage: "trash")
                            }
                        }
                }
            }
            .listStyle(.insetGrouped)
        }
    }

    private var filteredItems: [WishlistItem] {
        var result = allItems
        // Status filter
        if let filter = statusFilter {
            result = result.filter { $0.status == filter }
        }
        // Search filter
        guard !searchText.isEmpty else { return result }
        let query = searchText.lowercased()
        return result.filter {
            $0.partName.lowercased().contains(query) ||
            ($0.reason?.lowercased().contains(query) ?? false) ||
            ($0.notes?.lowercased().contains(query) ?? false) ||
            ($0.requestedBy?.lowercased().contains(query) ?? false)
        }
    }

    // MARK: - Row View

    private func wishlistRow(_ item: WishlistItem) -> some View {
        HStack(spacing: 12) {
            // Priority indicator bar
            RoundedRectangle(cornerRadius: 2)
                .fill(priorityColor(item.priority))
                .frame(width: 4, height: 44)

            VStack(alignment: .leading, spacing: 4) {
                HStack(spacing: 6) {
                    Text(item.partName)
                        .fontWeight(.medium)
                        .lineLimit(1)
                    priorityBadge(item.priority)
                }

                HStack(spacing: 8) {
                    Label("\(item.qtySuggested)", systemImage: "number")
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    sourceTypeBadge(item.sourceType)

                    if let reason = item.reason, !reason.isEmpty {
                        Text(reason)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                    }
                }

                if let requestedBy = item.requestedBy, !requestedBy.isEmpty {
                    Text("by \(requestedBy)")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 4) {
                statusBadge(item.status)

                if let date = item.createdAt {
                    Text(formatDate(date))
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
            }
        }
        .padding(.vertical, 4)
    }

    // MARK: - Badges

    // TODO: When WishlistItem gains a dueDate field, replace fallback with TimelinePriorityColor.color(priority:dueDateString:)
    private func priorityColor(_ priority: String) -> Color {
        return TimelinePriorityColor.fallbackColor(priority: priority)
    }

    private func priorityBadge(_ priority: String) -> some View {
        let color = priorityColor(priority)
        return Text(priority.capitalized)
            .font(.system(.caption2, weight: .semibold))
            .padding(.horizontal, 6)
            .padding(.vertical, 2)
            .background(Capsule().fill(color.opacity(0.15)))
            .foregroundStyle(color)
    }

    private func statusBadge(_ status: String) -> some View {
        let (label, color): (String, Color) = switch status {
        case "pending": ("Pending", .orange)
        case "approved": ("Approved", .green)
        case "dismissed": ("Dismissed", .secondary)
        case "sent_to_procurement": ("Procured", .purple)
        default: (status.capitalized, .secondary)
        }
        return Text(label)
            .font(.system(.caption2, weight: .semibold))
            .padding(.horizontal, 6)
            .padding(.vertical, 2)
            .background(Capsule().fill(color.opacity(0.15)))
            .foregroundStyle(color)
    }

    private func sourceTypeBadge(_ sourceType: String) -> some View {
        let (icon, label): (String, String) = switch sourceType {
        case "manual": ("hand.raised", "Manual")
        case "forecast": ("chart.line.uptrend.xyaxis", "Forecast")
        case "reorder": ("arrow.triangle.2.circlepath", "Reorder")
        default: ("questionmark", sourceType.capitalized)
        }
        return Label(label, systemImage: icon)
            .font(.caption2)
            .foregroundStyle(.blue)
    }

    // MARK: - Actions

    private func approveItem(_ item: WishlistItem) {
        guard let service = appCore.wishlistService else { loadError = "Service not available"; return }
        guard let id = item.id else { loadError = "Invalid item — missing ID"; return }
        let approver = appCore.currentUser?.displayName ?? "Unknown"
        do {
            try service.approveItem(id: id, by: approver)
            loadData()
        } catch {
            loadError = userFriendlyError(error, context: "load wishlist")
        }
    }

    private func dismissItem(_ item: WishlistItem) {
        guard let service = appCore.wishlistService else { loadError = "Service not available"; return }
        guard let id = item.id else { loadError = "Invalid item — missing ID"; return }
        let dismisser = appCore.currentUser?.displayName ?? "Unknown"
        do {
            try service.dismissItem(id: id, by: dismisser)
            loadData()
        } catch {
            loadError = userFriendlyError(error, context: "load wishlist")
        }
    }

    private func sendToProcurement(_ item: WishlistItem) {
        guard let service = appCore.wishlistService else { loadError = "Service not available"; return }
        guard let id = item.id else { loadError = "Invalid item — missing ID"; return }
        do {
            try service.sendToProcurement(id: id)
            loadData()
        } catch {
            loadError = userFriendlyError(error, context: "load wishlist")
        }
    }

    private func reopenItem(_ item: WishlistItem) {
        guard let service = appCore.wishlistService else { loadError = "Service not available"; return }
        guard let id = item.id else { loadError = "Invalid item — missing ID"; return }
        do {
            try service.reopenItem(id: id)
            loadData()
        } catch {
            loadError = userFriendlyError(error, context: "load wishlist")
        }
    }

    private func deleteItem(_ item: WishlistItem) {
        guard let service = appCore.wishlistService else { loadError = "Service not available"; return }
        guard let id = item.id else { loadError = "Invalid item — missing ID"; return }
        do {
            try service.deleteItem(id: id)
            loadData()
        } catch {
            loadError = userFriendlyError(error, context: "load wishlist")
        }
    }

    // MARK: - Data Loading

    private func loadData() {
        guard let service = appCore.wishlistService else {
            loadError = "Wishlist service not available"
            isLoading = false
            return
        }
        isLoading = allItems.isEmpty
        loadError = nil
        do {
            allItems = try service.listItems(status: nil)
        } catch {
            loadError = userFriendlyError(error, context: "load wishlist")
        }
        isLoading = false
    }

    // MARK: - Helpers

    private func formatDate(_ dateString: String) -> String {
        // Try ISO 8601 first, then fallback to SQLite datetime format
        let isoFormatter = ISO8601DateFormatter()
        isoFormatter.formatOptions = [.withInternetDateTime]

        let sqlFormatter = DateFormatter()
        sqlFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"

        let displayFormatter = DateFormatter()
        displayFormatter.dateStyle = .short
        displayFormatter.timeStyle = .none

        if let date = isoFormatter.date(from: dateString) {
            return displayFormatter.string(from: date)
        } else if let date = sqlFormatter.date(from: dateString) {
            return displayFormatter.string(from: date)
        }
        return dateString
    }
}

// MARK: - Add Wishlist Item Sheet

/// Sheet for adding a new wishlist item with part name, quantity, priority, and reason.
private struct AddWishlistItemSheet: View {
    @EnvironmentObject private var appCore: AppCore
    @Environment(\.dismiss) private var dismiss

    let onSave: () -> Void

    @State private var partName = ""
    @State private var qtySuggested = 1
    @State private var priority = "normal"
    @State private var reason = ""
    @State private var notes = ""
    @State private var saveError: String?
    @State private var isSaving = false

    private let priorities = ["urgent", "high", "normal", "low"]

    var body: some View {
        NavigationStack {
            Form {
                Section("Part Information") {
                    TextField("Part Name", text: $partName)
                        .textContentType(.none)

                    Stepper("Quantity: \(qtySuggested)", value: $qtySuggested, in: 1...9999)
                }

                Section("Priority") {
                    Picker("Priority", selection: $priority) {
                        ForEach(priorities, id: \.self) { p in
                            Label(p.capitalized, systemImage: priorityIcon(p))
                                .tag(p)
                        }
                    }
                    .pickerStyle(.segmented)
                }

                Section("Details") {
                    TextField("Reason (optional)", text: $reason, axis: .vertical)
                        .lineLimit(2...4)

                    TextField("Notes (optional)", text: $notes, axis: .vertical)
                        .lineLimit(2...4)
                }

                if let error = saveError {
                    Section {
                        Text(error)
                            .foregroundStyle(.red)
                            .font(.caption)
                    }
                }
            }
            .navigationTitle("Add Wishlist Item")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Add") { saveItem() }
                        .disabled(partName.trimmingCharacters(in: .whitespaces).isEmpty || isSaving)
                        .fontWeight(.semibold)
                }
            }
        }
    }

    private func priorityIcon(_ priority: String) -> String {
        switch priority {
        case "urgent": "exclamationmark.triangle"
        case "high": "arrow.up"
        case "normal": "minus"
        case "low": "arrow.down"
        default: "minus"
        }
    }

    private func saveItem() {
        guard let service = appCore.wishlistService else {
            saveError = "Wishlist service not available"
            return
        }

        let trimmedName = partName.trimmingCharacters(in: .whitespaces)
        guard !trimmedName.isEmpty else {
            saveError = "Part name is required"
            return
        }

        isSaving = true
        saveError = nil

        do {
            try service.addItem(
                partName: trimmedName,
                qtySuggested: qtySuggested,
                reason: reason.isEmpty ? nil : reason,
                priority: priority,
                sourceType: "manual",
                requestedBy: appCore.currentUser?.displayName,
                notes: notes.isEmpty ? nil : notes
            )
            onSave()
            dismiss()
        } catch {
            saveError = userFriendlyError(error, context: "save wishlist")
            isSaving = false
        }
    }
}
