-- ═══════════════════════════════════════════════════════════════════════
-- Migration 010: Clock-Out Questions & Daily Reports
-- Phase 4 — Customizable questionnaire system + auto-generated reports
-- ═══════════════════════════════════════════════════════════════════════

-- ═══ CLOCK-OUT QUESTION TEMPLATES (global, boss-managed) ═══════════════
-- These are the standard end-of-day questions every worker answers at clock-out.
-- Boss can add/remove/reorder via Settings > Clock-Out Questions.
CREATE TABLE IF NOT EXISTS clock_out_questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question_text TEXT NOT NULL,
    answer_type TEXT NOT NULL DEFAULT 'text'
        CHECK (answer_type IN ('text', 'yes_no', 'photo')),
    is_required INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,

    -- Metadata
    created_by INTEGER REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Seed default electrician clock-out questions
INSERT OR IGNORE INTO clock_out_questions (question_text, answer_type, is_required, sort_order) VALUES
    ('Have you entered the parts you used today?', 'yes_no', 1, 1),
    ('What are you planning on tomorrow?', 'text', 1, 2),
    ('Do we have the parts you need?', 'yes_no', 1, 3),
    ('Have you coordinated tomorrow work?', 'yes_no', 1, 4),
    ('Any safety concerns or hazards observed?', 'text', 0, 5),
    ('Is the job site clean and secured?', 'yes_no', 1, 6),
    ('Any equipment issues to report?', 'text', 0, 7),
    ('Did you complete your planned scope today?', 'yes_no', 0, 8);


-- ═══ ONE-TIME PER-JOB QUESTIONS ════════════════════════════════════════
-- Boss can send a one-time question to a specific worker (or all workers)
-- on a specific job. Shows as a banner at clock-in, answerable during the
-- day, enforced at clock-out if still unanswered.
CREATE TABLE IF NOT EXISTS one_time_questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES jobs(id),
    target_user_id INTEGER REFERENCES users(id),  -- NULL = ask everyone on the job
    question_text TEXT NOT NULL,
    answer_type TEXT NOT NULL DEFAULT 'text'
        CHECK (answer_type IN ('text', 'yes_no', 'photo')),

    -- Lifecycle
    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'answered', 'expired', 'cancelled')),

    -- Who/when
    created_by INTEGER NOT NULL REFERENCES users(id),
    answered_by INTEGER REFERENCES users(id),
    answer_text TEXT,
    answer_photo_path TEXT,
    shown_at_clock_in INTEGER NOT NULL DEFAULT 0,  -- was it displayed at clock-in?
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    answered_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_otq_job ON one_time_questions(job_id);
CREATE INDEX IF NOT EXISTS idx_otq_target ON one_time_questions(target_user_id);
CREATE INDEX IF NOT EXISTS idx_otq_status ON one_time_questions(status);


-- ═══ CLOCK-OUT RESPONSES (answers to global questions) ═════════════════
-- One row per question answered per clock-out session.
-- Links labor_entry (who/when) to clock_out_question (which question).
CREATE TABLE IF NOT EXISTS clock_out_responses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    labor_entry_id INTEGER NOT NULL REFERENCES labor_entries(id),
    question_id INTEGER NOT NULL REFERENCES clock_out_questions(id),

    -- Answer (type depends on question's answer_type)
    answer_text TEXT,               -- for 'text' type
    answer_bool INTEGER,            -- for 'yes_no' type (0=no, 1=yes)
    photo_path TEXT,                -- optional photo attachment per answer

    answered_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_cor_labor ON clock_out_responses(labor_entry_id);
CREATE INDEX IF NOT EXISTS idx_cor_question ON clock_out_responses(question_id);


-- ═══ DAILY REPORTS (auto-generated at midnight) ════════════════════════
-- One report per job per day. Generated by the midnight scheduler for any
-- job that had labor activity that day. Contains a JSON blob with all
-- worker clock data, question responses, parts consumed, and cost summary.
-- Rendered as a locked "notebook page" — read-only after generation.
CREATE TABLE IF NOT EXISTS daily_reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER NOT NULL REFERENCES jobs(id),
    report_date TEXT NOT NULL,     -- YYYY-MM-DD

    -- Generated content (structured JSON — rendered as locked notebook page)
    report_json TEXT NOT NULL,

    -- Status lifecycle
    status TEXT NOT NULL DEFAULT 'generated'
        CHECK (status IN ('generated', 'reviewed', 'locked')),
    generated_at TEXT NOT NULL DEFAULT (datetime('now')),
    reviewed_by INTEGER REFERENCES users(id),
    reviewed_at TEXT,

    UNIQUE(job_id, report_date)
);

CREATE INDEX IF NOT EXISTS idx_dr_job_date ON daily_reports(job_id, report_date);
CREATE INDEX IF NOT EXISTS idx_dr_date ON daily_reports(report_date);
